[package]
name = "rest-test"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
shuttle-rocket = "0.53.0"
shuttle-runtime = "0.53.0"

[dependencies.sqlx]
version = "^0.7"
features = []


[dependencies.rocket]
version = "0.5"
features = ["json"]

[dependencies.rocket_db_pools]
version = "0.1.0"
features = ["sqlx_sqlite"]
