[package]
name = "rest-test"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
shuttle-rocket = "^0.53"
shuttle-runtime = "^0.53"
shuttle-shared-db = { version = "^0.53", features = ["postgres", "sqlx"] }
tokio = "1.44.2"

[dependencies.sqlx]
version = "^0.8"
features = ["postgres"]

[dependencies.rocket]
version = "0.5"
features = ["json"]
